export enum EstadoPedido {
    PENDIENTE_PAGO = 'PENDIENTE_PAGO',
    EN_CAMINO = 'EN_CAMINO',
    CANCELADO = 'CANCELADO',
    COMPLETADO = 'COMPLETADO',
    PREPARACION = 'PREPARACION',
    CONFIRMAR = 'CONFIRMAR',
    LISTO = 'LISTO'
}